//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppP.T_0._1_
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolutionReference
    {
        public int ID { get; set; }
        public int TaskID { get; set; }
        public string Text { get; set; }
        public string Code { get; set; }
        public int ProgrammingLanguageID { get; set; }
    
        public virtual ProgrammingLanguage ProgrammingLanguage { get; set; }
        public virtual Task Task { get; set; }
    }
}
